### ISSUE TITLE
loadByProduct Fails for sls at TALL for 2019-06

### ISSUE THREAD

**Issue by walleo860** [NEONScience/NEON-utilities#114]
**Function**
loadByProduct seems to be broken with a specific dpid, date, and site.

**Describe the bug**
dpid <- 'DP1.10086.001'
site <- 'TALL'
date <- '2019-06'
  
  portaldata <- loadByProduct( dpID = dpid,
                                   site = site,
                                   startdate = date, 
                                   enddate = date,
                                   check.size = FALSE,
                                   token = Sys.getenv('NEON_TOKEN'),
                                   package = 'basic'
                                   ) 

results in:
` Error in read.table(file = file, header = header, sep = sep, quote = quote,  :   no lines available in input `
This follows immediately after 'Unpacking zip files using 1 cores.'

**Expected behavior**
I should be getting data or an error saying there is no data for the dp at that site at that month
 
**System (please complete the following information):**
 - R Version: 4.0.4

**Comment by cklunch** [comment]
The data files for DP1.10086.001 TALL 2019-06 are empty, see issue log: https://data.neonscience.org/data-products/DP1.10086.001
This was a publication error, and this is the only instance of it. If more than one product-site-month is downloaded, the empty files will be skipped; it's failing here because there are no data at all when this is the only product-site-month accessed. I'll see if I can handle this a little more smoothly in the next version, but in general neonUtilities wasn't built around handling data from a single site and month at a time, so there may be some strange behavior in that scenario.

**Comment by cklunch** [comment]
The data files are no longer empty in RELEASE-2022, and neonUtilities has been updated to handle empty files more smoothly.
