### ISSUE TITLE
External lab files are not stacked

### ISSUE THREAD

**Issue by chrlaney** [NEONScience/NEON-utilities#6]
For example, see microbe cell counts data product - each monthly package contains NEON.Argonne National Laboratory.amc_cellCountLabSummary.csv. These do not stack because their file naming convention differs from NEON data files naming conventions.

**Comment by sokole** [comment]
I don't think you want to stack these because the same table is often repeated in each zipped chunk (with the other data tables that do get stacked). I think the best option regarding the lab summary tables would be to take the one from the zipped chunk with the latest date return that with the other stacked files. --I think you may have already implemented something like this?

**Comment by chrlaney** [comment]
@sokole - I was actually thinking of a merge - no duplicates but make sure all info is available in the 'stacked file'. Or will the most recent version of the file always contain all of the data that a user might need?

**Comment by scelmendorf** [comment]
Most recent should contain the best

**Comment by chrlaney** [comment]
True for all data products with external lab data or just this product?

**Comment by scelmendorf** [comment]
Umm.  I am pretty sure true for all labs?

**Comment by chrlaney** [comment]
Ok, will go with that for now and revisit if we find another use case.

**Comment by chrlaney** [comment]
Will all of the lab summary files for various data products contain the string "labSummary" (and if not, make a convention)? er.... and is there a naming convention right now for lab files? Was surprised to see white spaces in file name.

**Comment by scelmendorf** [comment]
I have no idea - you would have to ask @cklunch

**Comment by cklunch** [comment]
The white spaces are in there because Dawn is creating the file names using the lab names, which have spaces. I wouldn't count on every one containing "labSummary." I think the cleanest way to handle these lab-current files would be the same as we did for the lab-all files (eg tck_pathogenqa), and only publish one copy with each download. Would that be hard to do?

**Comment by chrlaney** [comment]
Hi @ddlenz, please see Claire's comment and thread above. What do you think?

**Comment by ddlenz** [comment]
The filenames are generated per your specifications - if you want them changed, just let me know. Spaces aren't disallowed in named location names, but seem undesirable in filenames.

**Comment by chrlaney** [comment]
Thanks @ddlenz. @cklunch , I agree with your recommendation, could you please draft something - would help if there is consistency that we can key on across data products.

**Comment by cklunch** [comment]
The current format seems to be following the rules laid out here generically: https://github.com/NEONScience/how-to-make-a-data-product/blob/master/Publication%20workbook%20OS/defunct/pubInstructionsGenericOS.pdf and here in a specific case including a lab-specific file: https://github.com/NEONScience/biogeochemistryIPT/blob/master/StreamWaterChem/old%20def%20data%20(before%20L0%20decision)/pubInstructionsWaterChem.pdf

The lab-specific file instructions in the second document include putting _ in the spaces, I'd vote we stick with that. I can resurrect a new version of the generic pub instructions document, including instructions for lab-all, site-all, and lab-current files.

**Comment by chrlaney** [comment]
Added a new rule for handling Argonne lab file - find all, copy first one in the list to stackedFiles folder.
