### ISSUE TITLE
loadByProduct error when requesting Tick data at all sites (DP1.10093.001)

### ISSUE THREAD

**Issue by WynneMoss** [NEONScience/NEON-utilities#94]
**Function**
loadByProduct; data product DP1.10093.001

**Describe the bug**
Using loadByProduct to download Tick data (DP1.10093.001) results in an error when trying to download all sites. The error seems to occur after stacking, as it reports that stacking finished.

The error is:

> Error in list.files(folder, full.names = TRUE, pattern = zipPattern) : assertion 'tree->num_tags == num_tags' failed in executing regexp: file '../../../../../R-3.6.1/src/extra/tre/tre-compile.c', line 634

The error does not occur when downloading only a subset of sites, or downloading all sites of other data products.

**To Reproduce**

`Tick_all <- neonUtilities::loadByProduct(dpID = "DP1.10093.001",
                                        check.size = F)`

**Expected behavior**
Should download and stack data. The following code work as expected:

downloading all sites, other data:
`plant <- neonUtilities::loadByProduct(dpID = "DP1.10058.001", check.size = F)`
downloading tick data, specified sites:

`Tick_test <- neonUtilities::loadByProduct(dpID ='DP1.10093.001', site = c("HARV", "BLAN"), check.size = F)`

**System (please complete the following information):**
 - OS: iOS
 - OS Version: 10.15.4
 - R Version: 3.6.1 (another user reported same issue with 4.0)

**Additional context**
It seems like this might relate to the latest data release, as there were no errors with the same package version about 2 weeks ago.

**Comment by cklunch** [comment]
@WynneMoss Yep, this is an error in version 1.3.5. It happens when a large number of site by month files are stacked - I haven't determined the exact number, but I think somewhere around 500-600 site-months.

It's fixed in the version currently on GitHub. I still have several other updates to make before I send 1.3.6 to CRAN, but for now you can install from here to get around this bug. I'll comment and close this issue when it goes to CRAN. Thanks!

**Comment by WynneMoss** [comment]
Thanks @cklunch! Github version of the function is working.

**Comment by cklunch** [comment]
@WynneMoss Fixed version (1.3.6) is up on CRAN now. Thanks!
